FROM ubuntu:latest
WORKDIR /
ENV DEBIAN_FRONTEND="noninteractive" TZ="America/New_York"
RUN apt-get -y update
RUN apt-get -y install git curl wget
RUN apt-get -y install {LINUX_DEPENDENCIES}
COPY {SOURCE_DIR_PATH} {DESTINATION_DIR_PATH}/
CMD {COMMAND_ARRAY}